import { Footer, NavBar } from "@/components";
import "./globals.css";
import { Colors } from "@/utils/font/color";
import "@mantine/core/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#FFFFFF] w-full h-full p-4  md:p-5 antialiased`}>
        <MantineProvider>
          <NavBar />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
